from openvkbottle_types.methods.account import *
from openvkbottle_types.methods.ads import *
from openvkbottle_types.methods.app_widgets import *
from openvkbottle_types.methods.apps import *
from openvkbottle_types.methods.auth import *
from openvkbottle_types.methods.base_category import *
from openvkbottle_types.methods.board import *
from openvkbottle_types.methods.bugtracker import *
from openvkbottle_types.methods.database import *
from openvkbottle_types.methods.docs import *
from openvkbottle_types.methods.donut import *
from openvkbottle_types.methods.downloaded_games import *
from openvkbottle_types.methods.fave import *
from openvkbottle_types.methods.friends import *
from openvkbottle_types.methods.gifts import *
from openvkbottle_types.methods.groups import *
from openvkbottle_types.methods.lead_forms import *
from openvkbottle_types.methods.likes import *
from openvkbottle_types.methods.market import *
from openvkbottle_types.methods.messages import *
from openvkbottle_types.methods.newsfeed import *
from openvkbottle_types.methods.notes import *
from openvkbottle_types.methods.notifications import *
from openvkbottle_types.methods.orders import *
from openvkbottle_types.methods.pages import *
from openvkbottle_types.methods.photos import *
from openvkbottle_types.methods.podcasts import *
from openvkbottle_types.methods.polls import *
from openvkbottle_types.methods.pretty_cards import *
from openvkbottle_types.methods.search import *
from openvkbottle_types.methods.secure import *
from openvkbottle_types.methods.stats import *
from openvkbottle_types.methods.status import *
from openvkbottle_types.methods.storage import *
from openvkbottle_types.methods.store import *
from openvkbottle_types.methods.stories import *
from openvkbottle_types.methods.streaming import *
from openvkbottle_types.methods.translations import *
from openvkbottle_types.methods.users import *
from openvkbottle_types.methods.utils import *
from openvkbottle_types.methods.video import *
from openvkbottle_types.methods.wall import *
from openvkbottle_types.methods.widgets import *
